file = open('output.txt','w')
a=input("Enter text to write to the file: ")
file.write(a)
file.write("\n")
print("Data successfully written to output.txt. \n")
file.close()

file = open('output.txt','a')
b=input("Enter additional text to append: ")
file.write(b)
print("File successfully appended \n")
file.close()

print("Final content of output.txt:")
file=open('output.txt','r')
l=file.readline()
print(l)
l=file.readline()
print(l)
file.close()
